### PR TITLE
Zio2 upgrade

### PR DESCRIPTION
**Pull request by justcoon**
upgrade to zio2 #104

probably, side branch for ZIO2 should be created (like in other projects)

### CODE REVIEW

**Comment by justcoon** [comment]
I will update this one to zio 2 RC5

**Comment by zalbia** [comment]
Thank you for your contribution, @justcoon! Would you like to update this PR to the latest ZIO 2 version, along with the other dependencies?

**Comment by justcoon** [comment]
Hi @zalbia,
yeah I wanted to do that, spend some time with before with RC5, RC6 ...

but after this version, I probably did something wrong, or something change, that shutdown does not work properly 

those are latest changes which I did:
https://github.com/justcoon/zio-webhooks/compare/zio2...justcoon:zio-webhooks:zio2_final?expand=1

maybe you can check it, if you not find some issue there ...

**Comment by zalbia** [comment]
> Hi @zalbia, yeah I wanted to do that, spend some time with that before with RC5, RC6 ...
> 
> but after this version, I probably did something wrong, or something change, that shutdown does not work properly
> 
> those are latest changes which I did: https://github.com/justcoon/zio-webhooks/compare/zio2...justcoon:zio-webhooks:zio2_final?expand=1
> 
> maybe you can check it, if you not find some issue there ... i added some printLines there, it is look like that `RetryController` does not shutdown ...

@justcoon I'll take a look.

**Comment by zalbia** [comment]
Continued and closed in #154.

**Pull request closed without merging**
